// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.akmade.common.proto;

public interface MsgListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.akmade.common.proto.MsgList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.akmade.common.proto.Msg messages = 1;</code>
   */
  java.util.List<com.akmade.common.proto.Msg> 
      getMessagesList();
  /**
   * <code>repeated .com.akmade.common.proto.Msg messages = 1;</code>
   */
  com.akmade.common.proto.Msg getMessages(int index);
  /**
   * <code>repeated .com.akmade.common.proto.Msg messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .com.akmade.common.proto.Msg messages = 1;</code>
   */
  java.util.List<? extends com.akmade.common.proto.MsgOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .com.akmade.common.proto.Msg messages = 1;</code>
   */
  com.akmade.common.proto.MsgOrBuilder getMessagesOrBuilder(
      int index);
}
