// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.akmade.common.proto;

public interface MsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.akmade.common.proto.Msg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.akmade.common.proto.Msg.Severity severity = 1;</code>
   */
  int getSeverityValue();
  /**
   * <code>.com.akmade.common.proto.Msg.Severity severity = 1;</code>
   */
  com.akmade.common.proto.Msg.Severity getSeverity();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
